const cabiStationInformationMock = {
  data: {
    stations: [
      {
        rental_uris: {
          ios: "https://dc.lft.to/lastmile_qr_scan",
          android: "https://dc.lft.to/lastmile_qr_scan",
        },
        station_id: "88",
        short_name: "31609",
        electric_bike_surcharge_waiver: false,
        external_id: "0824a68f-1f3f-11e7-bf6b-3863bb334450",
        lat: 38.878693599396954,
        legacy_id: "88",
        eightd_has_key_dispenser: false,
        rental_methods: ["KEY", "CREDITCARD"],
        capacity: 19,
        name: "Maine Ave & 7th St SW",
        has_kiosk: true,
        eightd_station_services: [],
        lon: -77.02305436134338,
        region_id: "42",
        station_type: "classic",
      },
      {
        rental_uris: {
          ios: "https://dc.lft.to/lastmile_qr_scan",
          android: "https://dc.lft.to/lastmile_qr_scan",
        },
        station_id: "207",
        short_name: "31265",
        electric_bike_surcharge_waiver: false,
        external_id: "08254442-1f3f-11e7-bf6b-3863bb334450",
        lat: 38.90093,
        legacy_id: "207",
        eightd_has_key_dispenser: false,
        rental_methods: ["KEY", "CREDITCARD"],
        capacity: 19,
        name: "5th St & Massachusetts Ave NW",
        has_kiosk: true,
        eightd_station_services: [],
        lon: -77.018677,
        region_id: "42",
        station_type: "classic",
      },
      {
        station_type: "classic",
        electric_bike_surcharge_waiver: false,
        rental_uris: {
          ios: "https://dc.lft.to/lastmile_qr_scan",
          android: "https://dc.lft.to/lastmile_qr_scan",
        },
        eightd_station_services: [],
        lat: 38.856425,
        capacity: 17,
        lon: -77.049232,
        eightd_has_key_dispenser: false,
        has_kiosk: true,
        legacy_id: "3",
        region_id: "41",
        short_name: "31002",
        external_id: "08246c35-1f3f-11e7-bf6b-3863bb334450",
        station_id: "3",
        rental_methods: ["CREDITCARD", "KEY"],
        name: "Crystal Dr & 20th St S",
      },
    ],
  },
  last_updated: 1619971260,
  ttl: 5,
};

const cabiStationGeoJSON = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        coordinates: [-77.02305436134338, 38.878693599396954],
        type: "Point",
      },
      properties: {
        capacity: 19,
        name: "Maine Ave & 7th St SW",
        regionId: "42",
        stationId: "88",
      },
    },
    {
      type: "Feature",
      geometry: {
        coordinates: [-77.018677, 38.90093],
        type: "Point",
      },
      properties: {
        capacity: 19,
        name: "5th St & Massachusetts Ave NW",
        regionId: "42",
        stationId: "207",
      },
    },
    {
      type: "Feature",
      geometry: {
        coordinates: [-77.049232, 38.856425],
        type: "Point",
      },
      properties: {
        capacity: 17,
        name: "Crystal Dr & 20th St S",
        regionId: "41",
        stationId: "3",
      },
    },
  ],
};

const cabiStationStatus = {
  data: {
    stations: [
      {
        num_ebikes_available: 0,
        num_docks_disabled: 0,
        is_renting: 1,
        last_reported: 1621734453,
        is_returning: 1,
        is_installed: 1,
        station_status: "active",
        num_bikes_available: 17,
        station_id: "3",
        eightd_has_available_keys: false,
        legacy_id: "3",
        num_bikes_disabled: 0,
        num_docks_available: 0,
      },
      {
        num_ebikes_available: 1,
        num_docks_disabled: 0,
        is_renting: 1,
        last_reported: 1621788119,
        is_returning: 1,
        is_installed: 1,
        station_status: "active",
        num_bikes_available: 6,
        station_id: "88",
        eightd_has_available_keys: false,
        legacy_id: "88",
        num_bikes_disabled: 0,
        num_docks_available: 13,
      },
      {
        num_ebikes_available: 0,
        num_docks_disabled: 0,
        is_renting: 1,
        last_reported: 1621788326,
        is_returning: 1,
        is_installed: 1,
        station_status: "active",
        num_bikes_available: 15,
        station_id: "207",
        eightd_has_available_keys: false,
        legacy_id: "207",
        num_bikes_disabled: 1,
        num_docks_available: 3,
      },
    ],
  },
  last_updated: 1621788410,
  ttl: 5,
};

const mergedCabiGeoJSON = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        coordinates: [-77.02305436134338, 38.878693599396954],
        type: "Point",
      },
      properties: {
        capacity: 19,
        name: "Maine Ave & 7th St SW",
        regionId: "42",
        stationId: "88",
        isRenting: 1,
        ebikesAvailable: 1,
        docksAvailable: 13,
        docksDisabled: 0,
        bikesDisabled: 0,
        bikesAvailable: 6,
      },
    },
    {
      type: "Feature",
      geometry: {
        coordinates: [-77.018677, 38.90093],
        type: "Point",
      },
      properties: {
        capacity: 19,
        name: "5th St & Massachusetts Ave NW",
        regionId: "42",
        stationId: "207",
        isRenting: 1,
        ebikesAvailable: 0,
        docksAvailable: 3,
        docksDisabled: 0,
        bikesDisabled: 1,
        bikesAvailable: 15,
      },
    },
    {
      type: "Feature",
      geometry: {
        coordinates: [-77.049232, 38.856425],
        type: "Point",
      },
      properties: {
        capacity: 17,
        name: "Crystal Dr & 20th St S",
        regionId: "41",
        stationId: "3",
        isRenting: 1,
        ebikesAvailable: 0,
        docksAvailable: 0,
        docksDisabled: 0,
        bikesDisabled: 0,
        bikesAvailable: 17,
      },
    },
  ],
};

export {
  cabiStationInformationMock,
  cabiStationGeoJSON,
  cabiStationStatus,
  mergedCabiGeoJSON,
};
