const cabiProperties = {
  name: "Capital Bikeshare",
  vehicleType: "bikes",
  pointLayer: "cabi-stations-points",
  polygonFillOutlineColor: "#FFF",
  colorStop: {
    firstColor: "#ffd200",
    secondColor: "#ffba00",
    thirdColor: "#ffa200",
    fourthColor: "#ff8900",
    fifthColor: "#fc6f00",
    sixthColor: "#f65315",
    seventhColor: "#ee3122",
  },
  featureState: {
    availability: "totalBikesAvailable",
    capacity: "totalBikeCapacity",
    percentAvailable: "percentAvailable",
  },
};

const capitalBikeshare = {
  name: cabiProperties.name,
  vehicleType: cabiProperties.vehicleType,
  sourceId: "cabi-stations-source",
  pointLayerId: cabiProperties.pointLayer,
  pointCircleColor: "#ee3122",
  availability: {
    default: false,
    name: cabiProperties.name,
    menuText: "Capital Bikeshare availability",
    vehicleType: cabiProperties.vehicleType,
    featureStateName: cabiProperties.featureState.availability,
    pointLayerId: cabiProperties.pointLayer,
    polygonLayerId: "cabi-bikes-availability",
    polygonFillOutlineColor: cabiProperties.polygonFillOutlineColor,
    polygonFillColor: [
      "interpolate",
      ["linear"],
      ["feature-state", cabiProperties.featureState.availability],
      0,
      ["to-color", cabiProperties.colorStop.firstColor],
      50,
      ["to-color", cabiProperties.colorStop.secondColor],
      100,
      ["to-color", cabiProperties.colorStop.thirdColor],
      200,
      ["to-color", cabiProperties.colorStop.fourthColor],
      300,
      ["to-color", cabiProperties.colorStop.fifthColor],
      400,
      ["to-color", cabiProperties.colorStop.sixthColor],
      500,
      ["to-color", cabiProperties.colorStop.seventhColor],
    ],
  },
  capacity: {
    default: false,
    name: cabiProperties.name,
    menuText: "Capital Bikeshare capacity",
    vehicleType: cabiProperties.vehicleType,
    featureStateName: cabiProperties.featureState.capacity,
    pointLayerId: cabiProperties.pointLayer,
    polygonLayerId: "cabi-bikes-capacity",
    polygonFillOutlineColor: cabiProperties.polygonFillOutlineColor,
    polygonFillColor: [
      "interpolate",
      ["linear"],
      ["feature-state", cabiProperties.featureState.capacity],
      0,
      ["to-color", cabiProperties.colorStop.firstColor],
      50,
      ["to-color", cabiProperties.colorStop.secondColor],
      100,
      ["to-color", cabiProperties.colorStop.thirdColor],
      200,
      ["to-color", cabiProperties.colorStop.fourthColor],
      300,
      ["to-color", cabiProperties.colorStop.fifthColor],
      400,
      ["to-color", cabiProperties.colorStop.sixthColor],
      500,
      ["to-color", cabiProperties.colorStop.seventhColor],
    ],
  },
  percentAvailable: {
    default: false,
    name: cabiProperties.name,
    menuText: "Capital Bikeshare percent available",
    vehicleType: cabiProperties.vehicleType,
    featureStateName: cabiProperties.featureState.percentAvailable,
    pointLayerId: cabiProperties.pointLayer,
    polygonLayerId: "cabi-bikes-percent-available",
    polygonFillOutlineColor: cabiProperties.polygonFillOutlineColor,
    polygonFillColor: [
      "interpolate",
      ["linear"],
      ["feature-state", cabiProperties.featureState.percentAvailable],
      0,
      ["to-color", cabiProperties.colorStop.firstColor],
      15,
      ["to-color", cabiProperties.colorStop.secondColor],
      30,
      ["to-color", cabiProperties.colorStop.thirdColor],
      45,
      ["to-color", cabiProperties.colorStop.fourthColor],
      60,
      ["to-color", cabiProperties.colorStop.fifthColor],
      75,
      ["to-color", cabiProperties.colorStop.sixthColor],
      90,
      ["to-color", cabiProperties.colorStop.seventhColor],
    ],
  },
};

const helbiz = {
  default: true,
  url: "https://api.helbiz.com/admin/reporting/washington/gbfs/free_bike_status.json",
  name: "Helbiz",
  menuText: "Helbiz scooters",
  vehicleType: "scooters",
  featureStateName: "totalHelbizScooters",
  featureStateDisabledName: "totalDisabledHelbizScooters",
  sourceId: "helbiz-scooters-source",
  pointLayerId: "helbiz-scooters-points",
  pointCircleColor: "#004CBF",
  polygonLayerId: "total-helbiz-scooters",
  polygonFillOutlineColor: "#FFFFFF",
  polygonFillColor: [
    "interpolate",
    ["linear"],
    ["feature-state", "totalHelbizScooters"],
    0,
    ["to-color", "#e3ffff"],
    10,
    ["to-color", "#cbf8fb"],
    20,
    ["to-color", "#b1f1f9"],
    30,
    ["to-color", "#96eaf9"],
    40,
    ["to-color", "#78e2fa"],
    50,
    ["to-color", "#53dafc"],
    60,
    ["to-color", "#02d2ff"],
  ],
};

const spin = {
  default: false,
  name: "Spin",
  menuText: "Spin scooters",
  url: "https://gbfs.spin.pm/api/gbfs/v1/washington_dc/free_bike_status",
  vehicleType: "scooters",
  featureStateName: "totalSpinScooters",
  featureStateDisabledName: "totalDisabledSpinScooters",
  sourceId: "spin-scooters-source",
  pointLayerId: "spin-scooters-points",
  pointCircleColor: "#EE4B2B",
  polygonLayerId: "total-spin-scooters",
  polygonFillOutlineColor: "#FFFFFF",
  polygonFillColor: [
    "interpolate",
    ["linear"],
    ["feature-state", "totalSpinScooters"],
    0,
    ["to-color", "#ffd7cb"],
    25,
    ["to-color", "#ffc3b0"],
    50,
    ["to-color", "#ffaf97"],
    75,
    ["to-color", "#ff9b7e"],
    100,
    ["to-color", "#ff8565"],
    150,
    ["to-color", "#ff6f4e"],
    200,
    ["to-color", "#ff6b4a"],
  ],
};

const services = [
  helbiz,
  spin,
  capitalBikeshare.availability,
  capitalBikeshare.percentAvailable,
  capitalBikeshare.capacity,
];

export { services, spin, capitalBikeshare, helbiz };
